name: generate-sdks

# Trigger only on tag pushes
on:
  push:
    tags:
      - '*'

jobs:
  generate-sdks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Fern
        run: npm install -g fern-api

      - name: Generate and Release SDKs
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: fern generate --group production --version ${{ github.ref_name }} --log-level debug
      
