name: Publish Documentation

on:
  push:
    branches:
      - main 

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder Step
        run: echo "A GitHub workflow must contain at least one job with no dependencies. Can remove if we ever add `fern-check` to `publish-docs`."

  publish-docs:
    needs: fern-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Download Fern
        run: npm install -g fern-api

      - name: Generate and Publish Documentation with Fern
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --docs 
